<!DOCTYPE html>
<html>
    <head>

        <?php
include "portal_head.php";
?>

        <title>Die Hörspielmacher - Blog</title>
    </head>

    <!-- Version 25.07.16 -->
    <body>

        <!-- Gesamter Inhalt -->
        <div id="all" class="blog">
            <div class="center"><img src="../pics/hp/portal_logo-oben.png" width="582" height="132" alt="Logo"></div>

            <!--  Menue  -->
            <div id="menu">
                <a class="menu" href="portal_1portal.php">Start</a>&nbsp;&nbsp;|&nbsp;
                <a style="text-decoration: underline; color:rgb(241, 181, 0);" class="menu" href="portal_2blog.php">Blog</a>&nbsp;&nbsp;|&nbsp;
                <a class="menu" href="portal_3aktionen.php">Aktionen</a>&nbsp;&nbsp;|&nbsp;
                <a class="menu" href="portal_4uns.php">Über uns</a>&nbsp;&nbsp;|&nbsp;
                <!-- <a class="menu" href="portal_5guests.php?page=1&amp;view=0">Gästebuch</a> -->
            </div>

            <!-- Inhalt -->
            <div id="content" class="m_b_25">

                <!-- 3??? Bergmonster -->
                <div class="text_short m_b_10">
                    <div class="blog_header">26.09.2016 - Beitrag von Uli</div>
                    <h1>Ein Fall ohne Aufklärung – „Die drei ??? und das Bergmonster“</h1>
                    <p>„Die drei ??? und das Bergmonster“, erzählt von M. V. Carey und als Hörspiel 1980 erschienen, zählt zu den alten Drei-???-Folgen, in denen Peter Pasetti noch Alfred Hitchcock spricht und Andreas „Bob Andrews“ Fröhlich noch vor dem Stimmbruch steht (auch wenn er sich in dieser Folge bereits anbahnt), sprich es handelt sich um die „guten alten“ Drei-???-Folgen, an die man – beim Hören von Folgen wie „Fußball-Gangster“ (Folge  63), „Vampir im Internet“ (Folge 88) oder „Panik im Park“ (Folge 110) – wehmütig zurückdenkt. Trotzdem gestaltet sich dieses Abenteuer der drei ??? nicht wie ihre üblichen Fälle und widerspricht auch völlig den Prinzipien des Genres.</p>
                    <p>Zunächst einmal erweckt der Inhalt dieses Falls den Eindruck, als hätte man sich in der Kassettenbox vergriffen und eine „Fünf Freunde“-Folge eingelegt: Der Fall spielt im Umfeld einer abgelegenen Bergpension statt in Rocky Beach. Es gibt einen Zeltplatz, Wanderwege über Bergwiesen, einen im Sommer verwaisten Skihang, eine Erdbebenspalte, in der noch Schnee liegt, einen Feuerturm, eine Einsiedlerhütte, einen geschwätzigen Tankwart, der Geschichten von einem Monsterberg berichtet und „Fünf Freunde“-Erzähler Lutz Mackensy spricht Kenneth, einen der beiden irischen Brüder, die Onkel Titus auf dem Schrottplatz angestellt hat. Ist M.C. Carey ein Pseudonym für „Fünf Freunde“-Autorin Enid Blyton?</p>
                    <p>Schon der  Anlass dafür, dass Kenneth und Patrick mit den drei ??? ins Bergland aufbrechen, um zum ersten Mal ihre geliebte Cousine Kathleen (unangekündigt) aufzusuchen, ist denkwürdig: Onkel Titus und Tante Matilde haben plötzlich beschlossen, ihren Betrieb für 14 Tage ruhenzulassen und Ferien zu machen. Der Plot als solcher ist erstaunlich unlogisch und der Plan des Bösewichts (Mr. Hammond) unglaublich aufwendig, will er doch einerseits seine Frau (Mrs. Hammond), die Cousine Kathleen glücklicherweise haargenau gleicht, als Doppelgängerin einsetzen, um an Kathleens Geld zu kommen. Andererseits will er offenbar auch Kathleens Pension übernehmen, um dort in einem ausgeschachteten Becken ein Bergmonster als Attraktion zur Schau stellen.</p>
                    <p>Der Plan von Mr. Hammond wird natürlich durch die Ankunft der irischen Brüder und der Juniordetektive einer starken Belastungsprobe ausgesetzt und ist schließlich zum Scheitern verurteilt. Einen gewissen Reiz hat das Spiel mit der geklauten Identität natürlich, obgleich die talentierte Mrs. Hammond nicht in jeder Situation in ihrer neuen Rolle aufgeht und auch kein Gälisch sprechen kann. Auch erzeugt das Hörspiel neben der Star-Besetzung der drei ??? mit den markanten Stimmen von Josef Dahmen, Volker Brandt und Joachim Wolff und mit einer stimmungsvollen Naturatmosphäre, die schließlich in einem Feuerinferno kulminiert, das ein unachtsamer Tourist auslöst:<br>„Der Wald brennt [...]. Ich habe eine Kippe verloren und schon stand alles in Flammen!“</p>
                    <p>Die Besonderheit dieses Falls liegt nun aber an dem titelgebenden Bergmonster. Das Prinzip kennt man aus jeder Scooby-Doo-Episode: Wann immer jugendliche Detektive mit einem übernatürlichen Phänomen konfrontiert sind, einem Geist, einem Untoten, einem Monster stellt dieses sich am Ende des Abenteuers meist als fauler Zauber heraus und lässt sich rational erklären. Auch Sherlock Holmes zeichnet sich ja gerade durch sein analytisch-rationales Denken aus und übernatürliche Phänomene, die sein Umfeld schockieren, rekonstruiert er auf diese Weise. In dieser Tradition steht auch Justus Jonas: Wie oft zeigt er sich besonders dem ängstlichen Peter überlegen und versichert, dass es keine Drachen, keine Gespenster und  dergleichen gibt. Nach „Die drei ??? und das Bergmonster“ (Folge 14!) stelle ich mir ernsthaft die Frage, ob dieses Verhalten in den nachfolgenden Fällen gerechtfertigt ist.</p>
                    <p>Denn das mysteriöse Bergmonster, das im Laufe des Falles wahlweise als Bär oder großer barfüßiger Mann erklärt werden soll, entpuppt sich am Ende des Falls tatsächlich als unbekanntes behaartes Wesen, eine Art Yeti oder Bigfoot, über das am Ende der Mantel des Schweigens gelegt wird, um seine Existenz nicht zu gefährden. Dafür setzt sich insbesondere der „Naturforscher“  Mr. Smathers ein, der in einer Szene, die ihn mit Franz von Assisi gleichstellt,  ein Stinktier grault, mit um ihn versammelten Tieren spricht und sie auch füttert (sie gleichzeitig allerdings warnt, von Fremden Futter anzunehmen: „Sie verstehen, was passieren kann.“).</p>
                    <p>Es wundert nicht, dass die Meinungen über dieses etwas ungewöhnliche Ende auseinandergehen, positiv betrachtet:<br><br>
                    <ul>
                        <li>„Pedantische Hörer, die immer alles bis auf den letzten Krümel aufgeklärt haben wollten, wurden hier vor den Kopf gestoßen (prima!).“</li>
                    </ul><br>
                    Umgekehrt wird mit schmerzender Klarheit angemerkt:<br><br>
                    <ul>
                        <li>„Die drei ??? und das Bergmonster“  ist sicherlich die ungewöhnlichste aller Folgen, da sie als einzige keine wirkliche Auflösung bietet!“.</li>
                    </ul><br>
                    Vor allem müsste man jedes Mal, wenn Justus wieder davon spricht, dass es irgendein Monster, Ungeheuer oder Gespenst nicht gibt, ihm entgegenhalten:<br>
                    „Und was war damals mit dem Bergmonster?“<br><br>[Quelle Leserkommentare: http://www.europa-vinyl.de/ddf14.php3]</p>
                    <div class="center m_t_10">
                        <img src="../pics/blog/3fragezeichen.jpg"><br />
                        <span>Was wurde aus dem Bergmonster?</span>
                    </div>
                </div>

                <!-- Tommy Tomix -->
                <div class="text_short m_b_10">
                    <div class="blog_header">21.06.2013 - Beitrag von Uli</div>
                    <h1>Die Hörspielserie „Tommy Tomix – Geheimbund roter Puma“</h1>
                    <p>Dass die Bibliotheken nach und nach angefangen haben, alle Hörkassetten aus ihrem Bestand zu entfernen, war auf den ersten Blick der letzte Todesstoß für die Serie „Tommy Tomix“, die bei „Ariola Express“ Ende der 80er Jahre erschienen ist. Unter den Bewertungen, die Fünft- und Sechstklässler aus meiner Hörspiel-AG nach einer 15-minütigen Hörprobe der 4. Folge der Serie („Der Tod aus dem Koffer“) abgaben, finden sich folgende Stimmen: „unlogisch!!“, „falsch betont“, „komischer Dialekt“, „unrealistisch“, „nicht so gute Quali“. Wird hier von einer neuen, medienverwöhnten Generation ein kleines Serienjuwel zu Unrecht niedergemacht? Bevor ich zur besagten Folge komme, sei noch kurz die Grundkonstellation erwähnt, wobei eine schnelle Überprüfung der Standardcheckliste für solche Fälle genügen soll:</p>
                    <p>„Jugendliche Detektivbande, die teilweise aufsehenerregende Verbrechen löst?“<br />Abgehakt!<br /><br />„Origineller (Bei-)Name, mit dem man die Detektivbande gut identifizieren kann?“<br />Erfüllt: „Geheimbund roter Puma“!<br /><br />„Klassische Besetzung der Bande mit den vorgeschriebenen Typen, darunter der kluge Anführer, der Sportler, der lustige Dicke, der Computerfreak  bzw. Bücherwurm, die hübsche Gefährtin, die Nervensäge (auch kombinierbar)?“<br />Trifft zu: Tommy Tomix, Julka, Hexi und Lauscher.<br /><br />„Persönlicher Draht der Bande zur Polizei?“<br />Aber hallo: Kommissar Hundhammer ist der verlängerte Arm der Gruppe!<br /><br />„Knallige Titelmelodie mit Wiedererkennungswert?“<br />Volltreffer:  „Hey Tommy Tomix, wir machen alles klar, du und deine Freunde vom Geheimbund roter Puma.“</p>
                    <p>Na ausgezeichnet, so weit scheint alles in Ordnung zu sein. Kommen wir zur 4. Folge der Serie: „Der Tod aus dem Koffer“. Es wäre müßig, die ganze aufreibende Handlung der Folge hier auszubreiten, deshalb konzentriere ich mich auf wenige Beispiele. Dreh- und Angelpunkt der Handlung ist ein Terrorunternehmen, dessen Anschlagsziel erst im Lauf der Folge entwirrt wird. Damit es gelingt, benötigen die Terroristen jedoch erst einmal große Bargeldsummen und rauben einen Geldtransporter aus. Einer der Terroristen lässt jedoch am Tatort seinen Schlüsselbund mit Ledermäppchen liegen, in dem sein Name („Otto Paluschke“) und Wohnort („Plautzing“) vermerkt sind. Zudem ist das Mäppchen mit blauer Farbe verschmiert, da der Terrorist seine Wohnung am selben Tag frisch gestrichen hat – in jeder Hinsicht eine beachtliche Leistung. Diese zeigen auch noch andere: Nachdem Tommy Tomix und Julka die Fahrer des überfallenen Geldtransporters befreit und dabei auch den verschmierten Schlüsselbund gefunden haben, erstattet Tommy Kommissar Hundhammer Bericht – Sherlock Holmes trifft auf Hercule Poirot:</p>
                    <p><b>Hundhammer:</b> „Gut gemacht, Tommy – wie immer! Ich fahr gleich raus zum Tatort.“<br /><b>Tommy:</b> „Ach noch was, den Schlüsselbund hier. Den haben wir neben dem Geldtransporter gefunden. Den beiden aus dem Transport gehört er nicht, die hab ich gefragt.“<br /><b>Hundhammer:</b> „Ja Donnerwetter, Tommy – mit Namen und Adresse! Das heißt, dass er möglicherweise einem der Terroristen gehört. Und der heißt dann ‚Paluschke‘ und wohnt in ‚Plautzing‘!“<br /><b>Tommy:</b> „Ich nehme an, Sie fahren jetzt erst mal nach Plautzing und schicken einen Streifenwagen zum Tatort.“<br /><b>Hundhammer:</b> „Du bist nicht nur ein toller Tennisspieler, Tommy. Du hast auch das Zeug zu einem guten Kriminalisten.“</p>
                    <p>Dieses Lob verdient sicherlich auch jeder Hörer, der der Handlung bis hierhin gefolgt ist. Ein Nebenaspekt ist der Dialekt, in dem Hundhammer spricht: Sein Kunst-Bairisch passt nicht so recht zu dem Kunst-Berlinerisch der Fahrer des Geldtransporters. Und Guru, der spirituelle Vater der Pumabande, ein Inder, Schlittenhundeführer, „Spezialist für Wirtschafskriminalität“ und Fachmann der fernöstlichen Kampftechnik Kalarippayat, erinnert mit seiner Aussprache eher an einen gebürtigen US-Amerikaner, der nach Deutschland ausgewandert ist. Kleine Unstimmigkeiten sollten aber den Blick für das Ganze nicht verstellen. Kommissar Hundhammer wiederum unterläuft noch ein kleiner ärgerlicher Fehler. Denn nachdem der Terrorist und Sonntagsmaler Paluschke dingfest gemacht wurde, fährt ein zweiter Terrorist – aus Schock über die Festnahme von Paluschke – in Hundhammers Dienstwagen. Das quittiert „Hundi“ (Tommys Spitzname für den Kommissar) zwar mit den Worten „Ja so ein Penner!“, lässt sich aber mit einem gefälschten Ausweis (auf den Namen „Hans Henning von Socke Paulmann“) und einer dürftigen Ausrede („Diese Verhaftung – der Mann in den Handschellen. Da fragt man sich doch, was geschehen ist. Deshalb hab ich auch nix gesehen.“) abspeisen.</p>
                    <p>Eine unscheinbare Stelle, die den ganzen Charme der Serie treffend einzufangen mag, gebe ich hier auch noch im Originaldialog wieder (die Tramper Tommy Tomix und Julka haben sich soeben an der Straße absetzen lassen):<br /><br /><b>Julka:</b> „Das is‘ aber noch ein ganz schönes Stück [nach Hause].“<br /><b>Tommy:</b> „Macht nix, Julka, ich hab nämlich dort drüben mein Rad im Gebüsch versteckt.“<br /><b>Julka:</b> „Wie kommt das denn, Tommy?“<br /><b>Tommy:</b> „Ich war gestern mit Arco, meinem Schäferhund, unterwegs. Da kam Else Bartreiter vorbei und hat mich im Wagen mitgenommen und … das Rad hab ich einfach ins Gebüsch gestellt.“<br /><br />Nun wundert man sich etwas, weshalb Tommy Tomix mit seinem Hund und dem Rad unterwegs ist, aber gut, möglich wäre es. Warum Else Bartreiter ihm, der mit Rad und Hund unterwegs ist, angeboten hat, ihn (vermutlich mit Hund) mitzunehmen und warum Tommy das Angebot angenommen hat, obgleich er dafür sein Rad in einem Gebüsch an der Straße zurücklassen musste – na ja. Immerhin gesellt sich Else Bartreiter, die ansonsten nicht mehr in der Hörspielfolge auftaucht, zu einer ganzen Reihe von Personen mit lustig gemeinten Namen, z.B. das Terroristenpärchen „Spokoff“ oder der bereits genannte Tausendsassa „Otto Paluschke“. In exemplarischer Weise zeigt der kurze Dialog auch, wie man dem unwissenden Hörer elegant Informationen vermittelt: So muss Tommy seiner unzertrennlichen Freundin Julka beiläufig erklären, dass es sich bei „Arco“ um seinen Schäferhund handelt. Ein kleiner Wermutstropfen dieser tollen Passage ist der Umstand, dass man den Sprechern anhört, dass sie selbst nicht restlos überzeugt von dieser Geschichte sind. Schade, denn so hören sich leider auch viele Stellen des fein durchkomponierten Skripts hin und wieder abgelesen an.</p>
                    <p>Wer glaubt, damit sei die Geschichte erzählt, irrt sich aber gewaltig. Hier konnte ich nur einen Bruchteil der turbulenten Handlung andeuten, da noch weitere Terroristen, Verfolgungsjagden, Sprengsätze (die Folge heißt nicht umsonst „Der Tod aus dem Koffer“), brillante Schlussfolgerungen und unglaubliche Zufälle schließlich zur Lösung des Falls führen. Im Titelsong heißt es: <br /><br />„Hey Tommy Tomix, du bist der Größte auf der Welt<br />in 1000 Abenteuern unser Superheld.“<br /><br />Bei der Qualität von „Der Tod aus dem Koffer“ ist es rätselhaft, weshalb nur ganze 6 Folgen dieser 1000 Abenteuer als Hörspiel veröffentlicht wurden. Immerhin hat der Autor Rolf Kalmuczak, unter dessen Pseudonym „Robert Falck“ die Serie bei „Ariola Express“ erschien, glücklicherweise den Plot der „Tommy Tomix“-Folgen jeweils in einer TKKG-Folge wiederverwerten können (bei „Der Tod aus dem Koffer“ muss man daher zu „Feind aus der Vergangenheit“, dem 89. TKKG-Fall greifen). Damit bleibt „Tommy Tomix“ auch dem mp3-Zeitalter noch erhalten – alle Hörspielserienliebhaber können daher durchatmen.</p>
                    <div class="center m_t_10">
                        <img src="../pics/blog/tommy.jpg"><br />
                        <span>Perle aus den 80er Jahren: die Hörspielserie „Tommy Tomix“</span>
                    </div>
                </div>

                <!-- Clique vom Reitstall -->
                <div class="text m_b_10">
                    <div class="blog_header">29.04.2013 - Beitrag von Martin</div>
                    <h1>Ein Reiterhof ohne Pferde</h1>
                    <p>Pferdehörspiele haben eine lange Tradition in der Hörspielwelt. Zu den bekanntesten Vertretern des Genres gehören „Bibi und Tina“, „Wendy“ oder „Bille und Zottel“. Wer jedoch denkt, dass sich dabei alles um Pferde und das Ausreiten in die Natur dreht, irrt gewaltig. Viel spannender sind oft die Geschichten, die sich auf und um den Hof herum abspielen: Der Liebesbrief an den süßen Reitlehrer, das verlorene Amulett der Gräfin oder die Motorrad-Rally in der Heide. Da werden „Miss Dixie“, „Amadeus“ oder wie die tierischen Begleiter sonst heißen, häufig ganz vergessen.</p>
                    <p>Besonders stark ist dieses Phänomen bei der Serie „Die Clique vom Reitstallcafé“ ausgeprägt. Das merkt man bereits an den Titeln, die in John-Grisham-Manier (Artikel + Substantiv) kaum auf eine Reiterhofserie schließen lassen: „Die Tournee“, „Die Entführung“ oder „Die Radio-Show“.</p>
                    <p>Die Hexalogie entstand Ende der 1980er auf der Grundlage einer Foto-Love-Story der Zeitschrift Mädchen. Jede Folge beginnt mit einem Intro, in dem die einzelnen Charaktere inklusive Größe und Sternzeichen vorgestellt werden:<br />Da wäre zum Beispiel Peter, der fiese Sohn des Stallbesitzers, den alle nur Joe nennen (warum eigentlich?), der aber auch eine weiche Seite hat. Seine Schwester Anna-Maria liebt Pferde über alles und möchte einmal Tierärztin werden. Außerdem mag sie den gut aussehenden Reitlehrer Markus, auch wenn ihre Eltern dagegen sind. Stallbursche Christian, der Schulabbrecher und Naturliebhaber, hat ein Auge auf Tilli, den langweiligsten Charakter geworfen. Sie ist klein, Brillenträgerin, schüchtern und dann auch noch Sternzeichen Waage. Ihr Gegenstück ist ihre Freundin Ina (groß, attraktiv, Architektentochter), die lieber in teurer Pferdekleidung für Fotos posiert, als selbst aufs Ross zu steigen. Außerdem sind da noch Tina (warum gibt es eigentlich in jeder Pferdeserie eine Tina?) und der Tänzer Perry. Perrys Tanztalent ist jedoch deutlich besser ausgeprägt als seine Treue, was Tina recht bald zu spüren bekommt. Nachdem sie ihn extra heiratet, damit er nicht zurück in den Iran muss, betrügt er sie mit seiner Tanzpartnerin.</p>
                    <p>Bei der Sprechwahl ist die Crème de la Crème der deutschen Hörspielsprecher vertreten. So kommt es zum Konflikt zwischen Hofchef Joe (gesprochen von „Justus Jonas“ Oliver Rohrbeck) und dem einfach Reitlehrer Markus (gesprochen von „Tarzan“ Sascha Draeger). Auch viele der anderen bekannten 3-Fragezeichen- und TKKG-Sprecher sind im Cast mit dabei.</p>
                    <p>Wer selbst schon mal auf einem Reiterhof war, wird bemerkt haben, dass Pferde ruhige Tiere sind, die nicht andauernd Geräusche von sich geben. Da das Medium Hörspiel jedoch auf den Ton angewiesen ist, muss man die Tiere hören! Das führt dazu, dass der Zuchthengst „Dorian“ schon beim Füttern eines Apfels freudig wiehert, als hätte man ihn auf eine Stute losgelassen. Auch die Galoppszenen finden stets auf gut hörbarem Teerboden statt auf gut bereitbarem Waldboden statt.</p>
                    <p>Beim Durchhören der Serie merkt man, dass den Hörspielautoren irgendwann die Ideen ausgegangen sind, weil nach ein paar Folgen alle typischen Pferdegeschichten (der Reitunfall, das große Turnier, das verletzte Pferd) erzählt worden sind. Daher endet die Serie trotz bester Unterhaltung etwas abrupt nach nur sechs Folgen.</p>
                    <div class="center m_t_10">
                        <img src="../pics/blog/reitstall.jpg"><br />
                        <span>Viel Dramatik, wenig Pferde: Die Clique vom Reitstallcafé</span>
                    </div>
                </div>

                <!-- Prof. van Dusen -->
                <div class="text m_b_10">
                    <div class="blog_header">31.03.2013 - Beitrag von Uli</div>
                    <h1>Eine Unze Französisch – der erste Fall von Professor van Dusen</h1>
                    <p>Als ich vor kurzer Zeit zum ersten Mal eine Folge von „Professor van Dusen“ gehört habe, war mir das Etikett „Kultstatus“, das dieser Serie anhaftet, noch nicht bewusst. Vieles von dem, was es über die Serie zu erfahren gibt, findet sich auf der sehr liebevoll und detailreich gestalteten offiziellen Professor-van-Dusen-Seite. Die Figuren und ersten Geschichten, aus denen Autor Michael Koser die Hörspielserie entworfen hat, stammen von dem amerikanischen Schriftsteller Jacques Futrelle, der 1912 mit der Titanic untergangen ist. Ein zweites Detail aus Jacques Futrelles Biographie bringt mich wieder zurück zu dem ersten Fall der Serie („Eine Unze Radium“), den ich neulich gehört habe: Futrelle, der wohl ursprünglich John Heath Futrell hieß, französisierte seinen Namen zu Jacques Futrelle. Eine ähnliche Operation hat Michael Koser im ersten Van-Dusen-Fall vorgenommen.</p>
                    <p>Der Fall selbst stellt seine Hörer bei der Aufklärung des Verbrechens nicht gerade vor eine unlösbare Aufgabe und Professor van Dusen, auch bekannt als „Die Denkmaschine“, sollte sich nur mäßig herausgefordert fühlen. Immerhin nahmen bereits meine Sechstklässler in der Hörspiel-AG nach Verschwinden des Radiums mit ihrer Mensch-in-Koffer-Theorie („Ein Schlangenmensch!“, „Ein Kind!“, „Ein Liliputaner!“) die richtige Spur auf. Geradezu vorbildlich allerdings setzt dieses Hörspiel eine Rolle um, die mit Klaus Miedel (Zweistein!) einen phantastischen Sprecher gefunden hat. Es handelt sich um die Rolle des Monsieur Bertrand, dem kleinen Gehilfen der Haupttäterin (in seinen eigenen Worten auch „die große berühmte, sensationelle Manfredini“). Als gebürtiger Franzose, der des Englischen bzw. Deutschen nicht ganz mächtig ist, darf er alles tun, was für diesen Fall in klassischen Hörspielen vorgesehen ist:</p>
                    <p>Bertrand wechselt ständig zwischen seiner Muttersprache und der Zweitsprache hin und her. Dabei werden seltenere Französischvokabeln hörerfreundlich wiederholt („Sie kommen heraus, avec la valise, mit der Koffer“; „Was isch? Die große Manfredini in die prison, die Gefängnis? Impossible!“). Bertrand spricht alles Nicht-Französische mit einem dick aufgetragenen französischen Akzent aus und übernimmt ständig vermeintliche Strukturen seiner Erstsprache („Sie niescht wissen, wenn Sie ha-ben vor sisch.“) Bertrand muss selbstverständlich das kleine Einmaleins der bekannten Französischwörter in seinen Sätzen unterbringen (darunter „Sacrebleu!“, „N’est-ce pas?“, „Eh bien!“, „Pourquoi pas?“, „C’est dommage!“).</p>
                    <p>Dieses Muster des radebrechenden Ausländers funktioniert genauso gut und unterhaltsam auch in der anderen Hörspielserien, z.B. bei „Fünf Freunde und das Burgverlies“ mit der Rolle des Amerikaners Mr. Henning („Der contents, äh, der Inhalt von dem Keller …“ oder „Äh, für diese story müssen Sie sich einen Dümmeren aussuchen als mich, Sie alter Schwindler, Sie“).</p>
                    <p>In der Originalgeschichte („The Problem of the Lost Radium“) von Futrell bzw. Futrelle gibt es nun aber keinen französischen Diebesgehilfen, sondern einen deutschen „Count von Fitz“, dessen Englisch auch noch nicht auf der Höhe seiner Artistenkunst ist, wie folgende Aussagen nahelegen:<br />„Ach, Gott!” raged the little German. „Let me down, der chair in, ef you blease.”<br />„She iss der famous Mlle. Fanchon, und I am der marvellous midget, Count von Fritz.”<br />Das kann natürlich in einem Hörspiel nicht mehr funktionieren, in dem ohnehin alle Deutsch sprechen (obgleich die betreffenden Personen Amerikaner sind). Der Nationenwechsel ist daher beinah zwingend. Und wenn ein Klischee wie in „Eine Unze Radium“ auch noch so mustergültig präsentiert wird, muss man es fast schon wieder gernhaben.</p>
                    <div class="center m_t_10">
                        <img src="../pics/blog/vandusen.jpg"><br />
                    </div>
                </div>

                <!-- Jan Tenner -->
                <div class="text m_b_10">
                    <div class="blog_header">15.02.2013 - Beitrag von Martin</div>
                    <h1>Jan Tenner - 11 Jahre Warten auf eine Fortsetzung</h1>
                    <p>Jan Tenner ist meiner Meinung nach eine der besten, wenn nicht sogar die beste Sci-Fi-Hörspielserie meiner Kindheit. Auch 30 Jahre nach ihrer Veröffentlichung bietet die Serie noch immer spannende Abenteuer mit intelligenten und witzigen Dialogen.</p>
                    <p>Ich entdeckte die Serie Anfang der 90er Jahre, als mein Bruder die Folge "Entführung ins All" von einem Flohmarkt mitbrachte. Von da an begann die langjährige Suche nach weiteren Hörspielen der Serie. Ohne Auto für Flohmarktbesuche und Internet-Tauschbörsen wie eBay blieb uns nur die regelmäßige Fahrradfahrt ins benachbarte Dorf, wo ein kleiner Elektronikhandel gleich im Eingangsbereich einen Kassettenaufsteller stehen hatte, wie man sie heute in Zeiten der mp3-Downloads nicht mehr findet.</p>
                    <p>Doch leider wurde uns die Vorfreude auf neuen Hörsipelspaß meist schon direkt an der Tür genommen, wenn die Verkäuferin aus einer dunklen Ecke krächzte, dass keine neue Kassetten geliefert wurden und der nächste Liefertermin erst wieder in 3 Wochen ist. Ein konkrete Kassettenbestellung war - wieso auch immer - anscheinend nicht möglich. Trotzdem schafften wir es mit der Zeit, die Sammlung so aufzustocken, dass wir auch mehrteilige Geschichten wie "Das dunkle Imperium" (7 Folgen) oder "Der Stein der Macht" (9 Folgen) an einem verregneten Wochenende komplett durchhören konnten.</p>
                    <p>Im Abspann jeder Geschichte wurde der Titel der nächsten Folge genannt, was die Spannung und Kauflust nochmal steigerte. Die höchste Folgennummer meiner Sammlung war Folge 45 ("Zweisteins Rückkehr"), in der der Superbösewicht Zweistein nach langer Abwesenheit wieder aus der Versenkung auftauchte. Die Folge endete damit, dass Zweistein den Bordcomputer Mimo entführt und ihn zur Waffe umprogrammieren will. Daraus leitete sich auch der Titel von Folge 46 ab: "Mimo, der Rächer".</p>
                    <p>Natürlich war ich besonders an dieser Folge interessiert, weil ich wissen wollte, ob die Serie gut ausgeht oder sogar weitere Folgen geplant sind. Aber die Suche blieb erfolglos. Kein Geschäft hatte die Folge auf Lager oder konnte uns definitv sagen, ob sie überhaupt exisiterte. Somit blieb Folge 46 lange Zeit ein Mysterium. Einen erster Hinweis erhielt ich bei meiner ersten Internet-Rechnerche Mitte der 90er Jahre. Dort hieß es, dass das Skript zwar geschrieben, die Folge aber nicht produziert worden sei. Diese Tatsache stimmte mich zwar traurig, aber immerhin herrschte jetzt Klarheit.</p>
                    <p>Und dann kam Ende 2000 plötzlich das Gerücht auf, dass zum 20-jährigen Jubiläum der Serie doch noch die Folge "Mimo, der Rächer" veröffentlicht werden soll. Und tatsächlich, nur wenige Wochen später war die Folge bei Amazon bestellbar oder bei Napster downloadbar. Ich konnte es nicht erwarten, das Hörspiel zu hören, und man kann nur sagen: Das lange Warten hat sich gelohnt!<p>
                    <div class="center m_t_10">
                        <img src="../pics/blog/jantenner.jpg"><br />
                        <span>Meine "Jan Tenner"-Kassettensammlung</span>
                    </div>
                </div>
            </div>
        </div>
         <!-- Datenschutz und Impressum -->
         <div class="ds">
            <a href="datenschutz.html">Datenschutz</a>
            |
            <a href="impressum.html">Impressum</a>
        </div>
    </body>
</html>